In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report

In [43]:
data = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [44]:
df = pd.DataFrame(data)

In [45]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [46]:
df.columns.unique()

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [48]:
df.drop('customerID', axis=1, inplace=True)

In [49]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [50]:
df['gender'] = df['gender'].map({'Female':0,'Male':1})

In [51]:
df = pd.get_dummies(df, drop_first=True)

In [52]:
df

,gender,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,0,1,29.85,29.85,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,1,0,34,56.95,1889.50,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,1,0,2,53.85,108.15,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,1,0,45,42.30,1840.75,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,0,2,70.70,151.65,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,24,84.80,1990.50,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7039,0,0,72,103.20,7362.90,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7040,0,0,11,29.60,346.45,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7041,1,1,4,74.40,306.60,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7042,1,0,66,105.65,6844.50,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [53]:
df.isnull().sum()

gender                                    0
SeniorCitizen                             0
tenure                                    0
MonthlyCharges                            0
TotalCharges                             11
Partner_Yes                               0
Dependents_Yes                            0
PhoneService_Yes                          0
MultipleLines_No phone service            0
MultipleLines_Yes                         0
InternetService_Fiber optic               0
InternetService_No                        0
OnlineSecurity_No internet service        0
OnlineSecurity_Yes                        0
OnlineBackup_No internet service          0
OnlineBackup_Yes                          0
DeviceProtection_No internet service      0
DeviceProtection_Yes                      0
TechSupport_No internet service           0
TechSupport_Yes                           0
StreamingTV_No internet service           0
StreamingTV_Yes                           0
StreamingMovies_No internet service       0
StreamingMovies_Yes                       0
Contract_One year                         0
Contract_Two year                         0
PaperlessBilling_Yes                      0
PaymentMethod_Credit card (automatic)     0
PaymentMethod_Electronic check            0
PaymentMethod_Mailed check                0
Churn_Yes                                 0
dtype: int64

In [54]:
df['TotalCharges']=df['TotalCharges'].fillna(df['TotalCharges'].mean())

In [55]:
df = df.astype(float)

In [56]:
df

,gender,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0.0,0.0,1.0,29.85,29.85,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,34.0,56.95,1889.50,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,2.0,53.85,108.15,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,1.0,0.0,45.0,42.30,1840.75,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,2.0,70.70,151.65,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,24.0,84.80,1990.50,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
7039,0.0,0.0,72.0,103.20,7362.90,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
7040,0.0,0.0,11.0,29.60,346.45,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
7041,1.0,1.0,4.0,74.40,306.60,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
7042,1.0,0.0,66.0,105.65,6844.50,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [57]:
from sklearn.model_selection import train_test_split
x = df.drop('Churn_Yes', axis=1)
y = df['Churn_Yes']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [58]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [59]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [60]:
ylog = log.predict(x_test_scaled)
ylog

array([1., 0., 0., ..., 0., 0., 0.])

In [61]:
print(classification_report(y_test, ylog))

              precision    recall  f1-score   support

         0.0       0.86      0.90      0.88      1036
         1.0       0.69      0.60      0.64       373

    accuracy                           0.82      1409
   macro avg       0.77      0.75      0.76      1409
weighted avg       0.81      0.82      0.82      1409

In [62]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [63]:
yknn = knn.predict(x_test_scaled)
yknn

array([1., 0., 0., ..., 0., 0., 0.])

In [64]:
print(classification_report(y_test, yknn))

              precision    recall  f1-score   support

         0.0       0.83      0.86      0.85      1036
         1.0       0.57      0.52      0.55       373

    accuracy                           0.77      1409
   macro avg       0.70      0.69      0.70      1409
weighted avg       0.76      0.77      0.77      1409

In [65]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [66]:
ynb = nb.predict(x_test_scaled)

In [67]:
ynb

array([1., 0., 0., ..., 0., 0., 1.])

In [68]:
print(classification_report(y_test, ynb))

              precision    recall  f1-score   support

         0.0       0.94      0.58      0.72      1036
         1.0       0.44      0.89      0.59       373

    accuracy                           0.67      1409
   macro avg       0.69      0.74      0.65      1409
weighted avg       0.81      0.67      0.68      1409

In [69]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [70]:
ydt = dt.predict(x_test_scaled)

In [71]:
ydt

array([1., 1., 0., ..., 0., 0., 1.])

In [72]:
print(classification_report(y_test, ydt))

              precision    recall  f1-score   support

         0.0       0.81      0.80      0.80      1036
         1.0       0.46      0.46      0.46       373

    accuracy                           0.71      1409
   macro avg       0.63      0.63      0.63      1409
weighted avg       0.71      0.71      0.71      1409

In [73]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train,y_train)

SVC()

In [74]:
y_svm = svm.predict(x_test_scaled)

In [75]:
y_svm

array([1., 0., 0., ..., 0., 0., 0.])

In [76]:
print(classification_report(y_test, y_svm))

              precision    recall  f1-score   support

         0.0       0.84      0.91      0.88      1036
         1.0       0.69      0.53      0.60       373

    accuracy                           0.81      1409
   macro avg       0.77      0.72      0.74      1409
weighted avg       0.80      0.81      0.81      1409

In [77]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [78]:
y_rf = rf.predict(x_test_scaled)

In [79]:
y_rf

array([1., 0., 0., ..., 0., 0., 0.])

In [80]:
print(classification_report(y_test, y_rf))

              precision    recall  f1-score   support

         0.0       0.83      0.91      0.87      1036
         1.0       0.66      0.47      0.55       373

    accuracy                           0.80      1409
   macro avg       0.75      0.69      0.71      1409
weighted avg       0.78      0.80      0.79      1409

In [84]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [85]:
ygb = gb.predict(x_test_scaled)

In [86]:
ygb

array([1., 0., 0., ..., 0., 0., 1.])

In [88]:
print(classification_report(y_test, ygb))

              precision    recall  f1-score   support

         0.0       0.85      0.91      0.88      1036
         1.0       0.68      0.55      0.61       373

    accuracy                           0.81      1409
   macro avg       0.76      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [89]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(x_train,y_train)

AdaBoostClassifier()

In [90]:
y_ada = ada.predict(x_test_scaled)

In [91]:
y_ada

array([1., 0., 0., ..., 0., 0., 1.])

In [92]:
print(classification_report(y_test, y_ada))

              precision    recall  f1-score   support

         0.0       0.85      0.91      0.88      1036
         1.0       0.69      0.55      0.61       373

    accuracy                           0.81      1409
   macro avg       0.77      0.73      0.74      1409
weighted avg       0.81      0.81      0.81      1409

In [93]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [94]:
yxgb = xgb.predict(x_test_scaled)

In [95]:
yxgb

array([1, 0, 0, ..., 0, 0, 1])

In [96]:
print(classification_report(y_test, yxgb))

              precision    recall  f1-score   support

         0.0       0.84      0.89      0.86      1036
         1.0       0.64      0.53      0.58       373

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

In [101]:
models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}
from sklearn.model_selection import cross_val_score

for name, model in models.items():

    scores = cross_val_score(
        model,
        x_train,
        y_train,
        cv=5,
        scoring='accuracy'
    )

    print(name)
    print("CV Scores:", scores)
    print("Mean CV Score:", scores.mean())
    print()

Logistic Regression
CV Scores: [0.81011535 0.80922804 0.79769299 0.78881988 0.80373002]
Mean CV Score: 0.8019172546615371

KNN
CV Scores: [0.75776398 0.76397516 0.74090506 0.76308784 0.75754885]
Mean CV Score: 0.756656175482781

Decision Tree
CV Scores: [0.72670807 0.71872227 0.7364685  0.72937001 0.72024867]
Mean CV Score: 0.7263035046438067

Random Forest
CV Scores: [0.81100266 0.79503106 0.76663709 0.78793256 0.78507993]
Mean CV Score: 0.7891366601471076

In [106]:
from sklearn.ensemble import StackingClassifier
estimators = [
    ('knn', KNeighborsClassifier()),
    ('dt', DecisionTreeClassifier()),
    ('rf', RandomForestClassifier()),
    ('svc', SVC()),
    ('log', LogisticRegression()),
    ('gb', GradientBoostingClassifier()),
    ('ada', AdaBoostClassifier()),
    ('xgb', XGBClassifier()),
    ('nb', GaussianNB()),
    ('lr', LogisticRegression())
]
stack = StackingClassifier(estimators=estimators, final_estimator=KNeighborsClassifier())
stack.fit(x_train,y_train)

StackingClassifier(estimators=[('knn', KNeighborsClassifier()),
                               ('dt', DecisionTreeClassifier()),
                               ('rf', RandomForestClassifier()), ('svc', SVC()),
                               ('log', LogisticRegression()),
                               ('gb', GradientBoostingClassifier()),
                               ('ada', AdaBoostClassifier()),
                               ('xgb',
                                XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsam...
                                              learning_rate=None, max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None,
                                              max_depth=None, max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=None, n_jobs=None,
                                              num_parallel_tree=None, ...)),
                               ('nb', GaussianNB()),
                               ('lr', LogisticRegression())],
                   final_estimator=KNeighborsClassifier())

In [107]:
y_stack = stack.predict(x_test_scaled)

In [108]:
y_stack

array([1., 0., 0., ..., 0., 0., 1.])

In [109]:
print(classification_report(y_test, y_stack))

              precision    recall  f1-score   support

         0.0       0.83      0.87      0.85      1036
         1.0       0.60      0.52      0.56       373

    accuracy                           0.78      1409
   macro avg       0.72      0.70      0.70      1409
weighted avg       0.77      0.78      0.77      1409

In [110]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5,random_state=42)
kmeans.fit(x_train,y_train)

KMeans(n_clusters=5, random_state=42)

In [112]:
ykmeans = kmeans.predict(x_test_scaled)

In [113]:
ykmeans

array([4, 1, 1, ..., 1, 4, 4], dtype=int32)

In [114]:
print(classification_report(y_test, ykmeans))

              precision    recall  f1-score   support

         0.0       0.96      0.17      0.29      1036
         1.0       0.06      0.05      0.06       373
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0

    accuracy                           0.14      1409
   macro avg       0.21      0.04      0.07      1409
weighted avg       0.72      0.14      0.23      1409

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [122]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=5, min_samples=5)
dbscan.fit_predict(x_test_scaled)

array([0, 1, 1, ..., 1, 0, 0])

In [119]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit_transform(x_test_scaled)

array([[-0.13696759, -3.32658413],
       [ 5.10576869,  0.37205721],
       [ 6.02023524,  1.93022028],
       ...,
       [ 5.75820225,  0.6672528 ],
       [-1.32631331,  1.73663327],
       [ 0.14067964, -2.68795077]])

In [123]:
labels = dbscan.fit_predict(x_test_scaled)

print(set(labels))

{np.int64(0), np.int64(1)}